// Run: npm run wording — writes docs/wording.md: every text in the app, Kurdish and Arabic side by side,
// so a native speaker can review the wording without opening the app.
import { writeFileSync } from "node:fs";
import { dict } from "../src/i18n.tsx";

const ckb = dict.ckb as Record<string, string>;
const ar = dict.ar as Record<string, string>;
const cell = (s: string) => s.replace(/\|/g, "\\|");

const rows = Object.keys(ckb)
  .filter((k) => k !== "months")
  .map((k) => `| ${k} | ${cell(ckb[k])} | ${cell(ar[k])} |`);

const md = `# App wording review (Kurdish Sorani + Arabic)

Generated by \`npm run wording\` from src/i18n.tsx. **Edit the texts in src/i18n.tsx, not this file.**
Reviewers: please mark anything that sounds unnatural, too formal, or wrong. The key (first column) tells the developer which text to change.

Months (Kurdish): ${ckb.months.replace(/,/g, "، ")}
Months (Arabic): ${ar.months.replace(/,/g, "، ")}

| Key | Kurdish (کوردی) | Arabic (العربية) |
|---|---|---|
${rows.join("\n")}
`;
writeFileSync(new URL("../docs/wording.md", import.meta.url), md, "utf8");
console.log(`wrote docs/wording.md with ${rows.length} texts`);
